version: '3.4'

services:
  studentsandteachers:
    image: ${DOCKER_REGISTRY-}studentsandteachers
    build:
      context: .
      dockerfile: StudentsAndTeachers/Dockerfile
    depends_on:
      - db
  db:
    image: mysql:8.1.0
    container_name: mysql
    restart: always
    ports:
      - "5432:3306"
    environment: 
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db_for_cs
    volumes:
      - ./dbdata:/var/lib/mysql/